### PR TITLE
semantic commit messages

### PR DESCRIPTION
**Pull request by arnau-rius**
Commit Workflow

https://user-images.githubusercontent.com/32937662/217525105-1d4abc6a-363f-40e2-9d8a-203ef5cd227d.mov

What happens if commit has not the expected format?

https://user-images.githubusercontent.com/32937662/217555472-2cb171c5-df9d-431a-98a2-59c37f2b5ef5.mov

### CODE REVIEW

**Review by andresin87 — APPROVED** [review]

**Comment by acd02** [comment]
Will it catch it, if instead of running `npm run commit`, I run `git commit -m "invalid message"`?

**Comment by arnau-rius** [comment]
> Will it catch it, if instead of running `npm run commit`, I run `git commit -m "invalid message"`?

Yes sure, take a loot at the second video. It is exactly this case. 👍🏽

**Comment by acd02** [comment]
The resolution is too low 😄 🧓

**Review by acd02 — APPROVED** [review]

**Comment by arnau-rius** [comment]
> The resolution is too low 😄 🧓

I know :/ It only accepts videos with less than 10MB

**Comment by arnau-rius** [comment]
> The resolution is too low 😄 🧓

You can find the videos here: https://drive.google.com/drive/folders/1d-9VrrFHGD5ffJVrfzzzUMJ-cd80QeD1?usp=share_link

**Review by andresz1 — APPROVED** [review]

**Pull request merged**
