### PR TITLE
feat(input): clear button

### PR DESCRIPTION
**Pull request by Powerplex**
**TASK**: #887

### Description, Motivation and Context

This PR add the clear button:

- It’s optional
- Not focusable with the tab key
- When is clicked besides removing the value of the input it focus it
- It’s displayed automatically when the value of the input is not empty
- Custom click handlers to the button could be added
- When the input is focused and escape key is pressed the value of the input is removed
- Accessible name could be set by consumers

https://github.com/adevinta/spark/assets/6877967/c6983195-6710-4bc1-bfca-4df89b8a788c

### Types of changes
- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🧾 Documentation
- [x] 🧪 Test
- [x] 🧠 Refactor
- [x] 💄 Styles

### CODE REVIEW

**Review by turolopezsanabria — APPROVED** [review]

**Comment by turolopezsanabria** [comment]
Maybe not for this PR, but the border-radius is not ok in Chrome for iPhone 

IMG_8286

**Comment by andresz1** [comment]
> Maybe not for this PR, but the border-radius is not ok in Chrome for iPhone
> 
> IMG_8286

Thanks @turolopezsanabria I already opened a PR to fix it #1026

**Comment by andresin87** [comment]
image
image
image

I think there is too much space

**Comment by andresin87** [comment]
if the <Input /> gets a type="srearch" attr, what is the behavior given? Could we set it and hide the native clear icon?

**Comment by andresz1** [comment]
> image image image
> I think there is too much space

It's because of the "safety area" but we still need to check the spacing with the design team

**Comment by andresz1** [comment]
> if the gets a type="srearch" attr, what is the behavior given? Could we set it and hide the native clear icon when including it as a prop or detecting the ClearButton inside ?

Yes! you are right. We need to hide it. We can do it in another PR

**Review by andresz1 — APPROVED** [review]

**Comment by andresin87** [comment]
I dnt know why we are using the <IconButton> with that space. I think we agree this should be fully clickable last wednesday. Can you please confirm if i'm wrong?

**Review by kikoruiz — APPROVED** [review]

**Comment by turolopezsanabria** [comment]
Sorry for being late: Yes it's correct @andresin87, the area should be fully clickable

> I don't know why we are using that space. I think we agree this should be fully clickable last Wednesday. Can you please confirm if I'm wrong?

**Pull request merged**
